### PR TITLE
add the sort func for songs

### PR DESCRIPTION
**Pull request by ArshErgon**
for the issue: #2 I have implemented the sorting function to sort the songs for the index.json with there title

### CODE REVIEW

**Review by eutampieri — CHANGES_REQUESTED** [review]
LGTM.
Could you please restore example.json.sample?

**Comment by ArshErgon** [comment]
@eutampieri its done.

**Review by eutampieri — APPROVED** [review]
LGTM

**Comment by eutampieri** [comment]
Thanks

**Pull request merged**
